version: '3'
services:
  scraper:
    build: .
    container_name: scraper-container
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./data/raw:/app/data/raw  # Mount local folder to Docker container
      - ./logs:/app/logs           # Mount logs folder to Docker container
    restart: unless-stopped
    entrypoint: ["sh", "-c", "while true; do python src/scraping/main.py; sleep 3 86400; done"]
